### ISSUE TITLE
JPAQuery.orderBy pass multi-params throw IllegalArgumentException

### ISSUE THREAD

**Issue by leeaee** [actframework/act-jpa-common#12]
JPAQuery.orderBy work fine with one parameter but throw an exception when multi-parameters input.
```java
    private JPAQuery<Admin> query(Map<String, String> params, Pageable page) {
        JPAQuery<Admin> query;
        if (params.size() == 0) {
            query = q();
        } else {
            query = q(getFields(params), getValues(params));
        }
        if (page.getOrder() != null) {
            query.orderBy("email DESC", "login_name ASC");
        }
        return query.offset(page.getOffset()).limit(page.getSize());
    }
```
When call query.fetch() method, will thrown an exception:
```log
2018-07-04 11:43:24,106 ERROR [XNIO-1 task-1] [act.handler.builtin.controller.RequestHandlerProxy] - Error handling request: [GET] /api/admin
java.lang.IllegalArgumentException: An exception occurred while creating a query in EntityManager: 
Exception Description: Problem compiling [SELECT Admin FROM Admin Admin  WHERE Admin.loginName = ?1 ORDER BY Admin.email DESC, Admin.login_name]. 
[84, 100] The state field path 'Admin.login_name' cannot be resolved to a valid type.
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.createQuery(EntityManagerImpl.java:1743)
	at act.db.jpa.JPAQuery.q(JPAQuery.java:360)
	at act.db.jpa.JPAQuery.fetch(JPAQuery.java:146)
	at cc.bable.data.dao.AdminDao.search(AdminDao.java:50)
```

**Comment by leeaee** [comment]
The issue seems not appear in org.actframework:act-jpa-common:1.5.1. I will keep monitoring it for more scenarios to confirm this has fixed.
