### ISSUE TITLE
JPAQuery.count throw IllegalStateException

### ISSUE THREAD

**Issue by leeaee** [actframework/act-jpa-common#13]
Using JPAQuery to query data as a list, the JPAQuery.fetch() could return value correctly, but JPAQuery.count() failed with exception.

```java
    public Page<Admin> search(Map<String, String> params, Pageable page) {
        JPAQuery<Admin> query = query(params, page);
        return new Page<>(query.fetch(), page, query.count());
    }
```
When execute the query.count(), failed
```log
2018-07-04 12:15:57,586 DEBUG [XNIO-1 task-1] [eclipselink.logging.sql] - SELECT ID, create_time, EMAIL, last_update, login_name, MOBILE, NAME, PASSWORD, PHONE, SALT, STATE, VERSION FROM bb_admin WHERE (login_name = ?) ORDER BY EMAIL DESC
	bind => [admin]
2018-07-04 12:15:58,628 ERROR [XNIO-1 task-1] [act.handler.builtin.controller.RequestHandlerProxy] - Error handling request: [GET] /api/admin
java.lang.IllegalStateException: Query argument 1 not found in the list of parameters provided during query execution.
	at org.eclipse.persistence.internal.jpa.QueryImpl.processParameters(QueryImpl.java:590)
	at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:181)
	at org.eclipse.persistence.internal.jpa.QueryImpl.getSingleResult(QueryImpl.java:528)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.getSingleResult(EJBQueryImpl.java:402)
	at act.db.jpa.JPAQuery.count(JPAQuery.java:154)
	at act.db.jpa.JPAQuery.count(JPAQuery.java:152)
	at cc.bable.data.dao.AdminDao.search(AdminDao.java:50)
```
JPAQuery object for fetch()
![image](https://user-images.githubusercontent.com/1191314/42256539-8de7b0b4-7f84-11e8-90c8-3bdfe046a2bb.png)
JPAQuery object for count()
![cp_ kxmq8 s yy u h](https://user-images.githubusercontent.com/1191314/42256572-c0b8b5a6-7f84-11e8-8be9-6d644641a100.png)
It seems the params has missing in count().

**Comment by leeaee** [comment]
This issue has fixed in org.actframework:act-jpa-common:1.5.1
