### ISSUE TITLE
Query 执行sql语句 Executing an update/delete query

### ISSUE THREAD

**Issue by wd0472** [actframework/act-jpa-common#17]
javax.persistence.Query query = em.createQuery(sql);
		for (int i = 0; i < values.length; ++i) {
			query.setParameter(i + 1, values[i]);
		}
query.executeUpdate();

javax.persistence.TransactionRequiredException: Executing an update/delete query
	at org.hibernate.jpa.spi.AbstractQueryImpl.executeUpdate(AbstractQueryImpl.java:54)
	at com.wykj.mcs.others.bases.BaseController.u(BaseController.java:515)
	at com.wykj.mcs.controllers.Application.updateaa(Application.java:150)
	at com.wykj.mcs.controllers.ApplicationMethodAccess.invoke(Unknown Source)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:839)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:504)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:48)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:517)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:203)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1106)
	at act.route.Router$ContextualHandler.handle(Router.java:1595)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:160)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by greenlaw110** [comment]
You need to start the transaction:

```java
javax.persistence.Query query = em.createQuery(sql);
for (int i = 0; i < values.length; ++i) {
    query.setParameter(i + 1, values[i]);
}
em.getTransaction().start();
try {
    query.executeUpdate();
    em.getTransaction().commit();
} catch (Exception e) {
    em.getTransaction().rollback();
}
```
