### ISSUE TITLE
Add @Transactional execute failed with exception

### ISSUE THREAD

**Issue by leeaee** [actframework/act-jpa-common#29]
ActFramework v1.8.8-RC12-SNAPSHOT-8ce7

```java
    @PostAction("signup")
    public Map<String, String> signUp(User user, ActionContext context) {
        conflictIf(dao.hasUser(user), context.i18n(Messages.ENTITY_ALREADY_EXIST, User.KEY, user.id));
        if (null != user.plainPassword) {
            user.password = Act.crypto().passwordHash(user.plainPassword);
        }
        saveUser(user);
        return C.Map("message", "201 Created");
    }

    @Transactional
    private void saveUser(User user) {
        dao.save(user);
    }
```

```log
2018-09-17 16:47:02.120 [XNIO-1 task-1] ERROR a.h.b.c.RequestHandlerProxy - Error handling request: [POST] /api/v1/signup
java.lang.IllegalStateException: null
	at org.osgl.util.E.illegalStateIf(E.java:726)
	at act.db.sql.tx.TxContext.enterTxScope(TxContext.java:47)
	at act.db.sql.tx.TxScopeHelper.enter(TxScopeHelper.java:31)
	at com.lingxian.probe.api.LoginEndpoint.saveUser(LoginEndpoint.java)
	at com.lingxian.probe.api.LoginEndpoint.signUp(LoginEndpoint.java:73)
	at com.lingxian.probe.api.LoginEndpointMethodAccess.invoke(Unknown Source)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:878)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:540)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:48)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:546)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:210)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1267)
	at act.route.Router$ContextualHandler.handle(Router.java:1601)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by leeaee** [comment]
The issue could not reappear in the local project now.
Closed it now and reopen when meeting again.
