### ISSUE TITLE
JPA could not support multi-save method in one transaction

### ISSUE THREAD

**Issue by leeaee** [actframework/act-jpa-common#30]
The code is like:
```java
    @Transactional
    private void authenticate(String username, String password, Auth auth, ActionContext context) {
        User user = dao.findOneBy(auth.getField(), auth == Auth.WECHAT ? getOpenId(username) : username);
        if (auth == Auth.WECHAT) {
            if (null == user) {
                user = new User();
                user.openId = username;
                user.roles = SecurityService.ROLE_NEW;
		user.auth = auth;
                dao.save(user);
            }
        } else if (auth == Auth.PHONE) {
            if (null == user || !Act.crypto().verifyPassword(password, user.password)) {
                throw unauthorized(403001, context.i18n(Messages.ENTITY_NOT_FOUND, User.KEY, username));
            } else {
                dao.save(user, "auth", auth);
            }
        }
    }
```
The first if logic can run normally, but when enter second if logic, it will throw JPA exception:
```trace
java.lang.NullPointerException: null
	at org.osgl.Lang.requireNotNull(Lang.java:6961)
	at act.db.jpa.JPAQuery.<init>(JPAQuery.java:57)
	at act.db.jpa.JPADao.createUpdateQuery(JPADao.java:298)
	at act.db.jpa.JPADao.save(JPADao.java:163)
	at com.lingxian.probe.api.LoginEndpoint.authenticate(LoginEndpoint.java:73)
	at com.lingxian.probe.api.LoginEndpoint.login(LoginEndpoint.java:47)
	at com.lingxian.probe.api.LoginEndpointMethodAccess.invoke(Unknown Source)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:878)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:540)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:48)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:546)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:210)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1267)
	at act.route.Router$ContextualHandler.handle(Router.java:1601)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by leeaee** [comment]
The issue could not reappear in the local project now.
