### ISSUE TITLE
ACT JPA will throw IllegalStateException readom

### ISSUE THREAD

**Issue by leeaee** [actframework/act-jpa-common#34]
Sometimes, ACT JPA will throw IllegalStateException readom when running, and it will auto recovery after recall the interafce.

```log
2018-10-22 21:28:42.258 [XNIO-1 task-1] ERROR a.x.NetworkHandler - Error handling network request
java.lang.IllegalStateException: JPAContext already set
	at org.osgl.util.E.illegalStateIf(E.java:753)
	at act.db.jpa.JPAContext.init(JPAContext.java:224)
	at act.db.jpa.JPAPlugin$4.on(JPAPlugin.java:98)
	at act.event.EventBus.callOn(EventBus.java:1310)
	at act.event.EventBus.callOn(EventBus.java:1332)
	at act.event.EventBus.callOn(EventBus.java:1367)
	at act.event.EventBus._emitWithOnceBus(EventBus.java:1283)
	at act.event.EventBus.emit(EventBus.java:847)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:159)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by greenlaw110** [comment]
This should be fixed by https://github.com/actframework/actframework/issues/895. @leeaee can you please verify it?
